djtutor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', 'home')),
    path('', include('django.contrib.auth.urls')),

    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'home'
urlpatterns = [
    path('', TemplateView.as_view(template_name='home/index.html'), name='index'),
    path('quote/', TemplateView.as_view(template_name='home/quote.html'), name='quote'),
    path('download/', TemplateView.as_view(template_name='home/download.html'), name='download'),
    path('about/', TemplateView.as_view(template_name='home/about.html'), name='about'),
]

home/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    class Meta:
        db_table = "auth_user"
        verbose_name_plural = '用户'
    pass

# 广告位

# 产品

#

home/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load ehcofilter %}
<!DOCTYPE html>
<html lang="zh">
<head>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% settings_value "TITLE" %}</title>
    <link rel="stylesheet" href="/static/vendor/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/static/vendor/css/fontawesome.all.css">
    <link rel="stylesheet" href="/static/vendor/css/bulma.css">
    <link rel="stylesheet" href="/static/home/css/common.css">

    {% block styles %} {% endblock %}
</head>

<body>
    <div id="app">
        {% include 'header.html' %}

        {% block content %} {% endblock %}
    </div>

    {% include 'footer.html' %}

    <script src="/static/vendor/js/vue.js"></script>
    {% include 'components/notification.html' %}
    {% include 'components/nav.html' %}

    {% block scripts %} {% endblock %}

    <script type="text/javascript">
        new Vue({
            delimiters: ['[[', ']]'],
            el: "#app"
        })
    </script>
</body>

</html>

templates/components/carousel.html
<script type="text/javascript">
    Vue.component('carousel',{
        delimiters: ['[[', ']]'],
        data: function () {
            return {
                slideList: [
                    {
                        "clickUrl": "#",
                        "desc": "nhwc",
                        "image": "/static/img/20181020121039SL9ON0leQQVSuM5760.png"
                    },
                    {
                        "clickUrl": "#",
                        "desc": "hxrj",
                        "image": "/static/img/20180320100329wWdw1U4rx7wgBK8819.png"
                    },
                    {
                        "clickUrl": "#",
                        "desc": "rsdh",
                        "image": "/static/img/20180319160333WBGNcwnuWlmEgr7744.jpg"
                    },
                    {
                        "clickUrl": "#",
                        "desc": "rsdh",
                        "image": "/static/img/20170306170342bqIwcTETm73BCH1960.png"
                    },
                    {
                        "clickUrl": "#",
                        "desc": "rsdh",
                        "image": "/static/img/20180321150329648X95sTsbTrD4186.png"
                    }
                ],
                currentIndex: 0,
                timer: ''
            }
        },
        created: function() {
            //在DOM加载完成后，下个tick中开始轮播
            this.$nextTick(() => {
                this.timer = setInterval(() => {
                    this.autoPlay()
                }, 4000)
            })
        },
        methods: {
            go: function() {
                this.timer = setInterval(() => {
                    this.autoPlay()
                }, 4000)
            },
            stop: function() {
                clearInterval(this.timer)
                this.timer = null
            },
            change: function(index) {
                this.currentIndex = index
            },
            autoPlay: function() {
                this.currentIndex++
                if (this.currentIndex > this.slideList.length - 1) {
                    this.currentIndex = 0
                }
            }
        },
        template: `
<div class="carousel-wrap">
    <transition-group tag="ul" class='slide-ul' name="list">
      <li v-for="(list,index) in slideList" :key="index" v-show="index===currentIndex" @mouseenter="stop" @mouseleave="go">
        <a :href="list.clickUrl" >
          <img :src="list.image" :alt="list.desc" width="672" height="394">
        </a>
      </li>
    </transition-group>
    <div class="carousel-items">
      <span v-for="(item,index) in slideList.length" :class="{'active':index===currentIndex}" @mouseover="change(index)"></span>
    </div>
</div>`
    })

</script>

<style type="text/css">

.carousel-wrap {
  position: relative;
  height: 453px;
  width: 100%;
  overflow: hidden;
  // 删除
  background-color: #fff;
}

.slide-ul {
    width: 100%;
    height: 100%;
}
.slide-ul li {
    position: absolute;
    width: 100%;
    height: 394px;
}
.slide-ul img {
    width: 100%;
    height: 100%;
}

.carousel-items {
    position: absolute;
    z-index: 10;
    top: 370px;
    width: 100%;
    margin: 0 auto;
    text-align: center;
    font-size: 0;
}
.carousel-items span {
    display: inline-block;
    height: 10px;
    width: 10px;
    margin: 0 3px;
    border: 1px solid #b2b2b2;
    background-color: white;
    cursor: pointer;
}
.carousel-items .active {
    background-color: #EF4202;
}

.list-enter-to {
  transition: all 1s ease;
  transform: translateX(0);
}

.list-leave-active {
  transition: all 1s ease;
  transform: translateX(-100%)
}

.list-enter {
  transform: translateX(100%)
}

.list-leave {
  transform: translateX(0)
}
</style>

templates/components/notification.html
<script type="text/javascript">
    Vue.component('notification', {
        delimiters:['[[', ']]'],
        // el: '#gonggao',
        data: function() {
            return {
              closed: false
            }
        },
        methods: {
            closeNotify: function() {
                this.closed = true
            }
        },
        template: `
        <div class="notification is-warning no-round" v-if="!closed" style="margin: 5px 0">
          <button class="delete" v-on:click="closeNotify"></button>
          <slot></slot>
        </div>
        `
    })
</script>

templates/components/tab.html
<script>
    Vue.component('tabs', {
        delimiters: ['[[', ']]'],
        props: {
            value: Number,
            expanded: Boolean,
            type: String,
            size: String,
            position: String,
            animated: {
                type: Boolean,
                default: true
            }
        },
        data() {
            return {
                activeTab: this.value || 0,
                tabItems: [],
                contentHeight: 0,
                _isTabs: true // Used internally by TabItem
            }
        },
        computed: {
            navClasses() {
                return [
                    this.type,
                    this.size,
                    this.position,
                    {
                        'is-fullwidth': this.expanded,
                        'is-toggle-rounded is-toggle': this.type === 'is-toggle-rounded'
                    }
                ]
            }
        },
        watch: {
            /**
             * When v-model is changed set the new active tab.
             */
            value(value) {
                this.changeTab(value)
            },
            /**
             * When tab-items are updated, set active one.
             */
            tabItems() {
                if (this.tabItems.length) {
                    this.tabItems[this.activeTab].isActive = true
                }
            }
        },
        methods: {
            /**
             * Change the active tab and emit change event.
             */
            changeTab(newIndex) {
                if (this.activeTab === newIndex) return
                this.tabItems[this.activeTab].deactivate(this.activeTab, newIndex)
                this.tabItems[newIndex].activate(this.activeTab, newIndex)
                this.activeTab = newIndex
                this.$emit('change', newIndex)
            },
            /**
             * Tab click listener, emit input event and change active tab.
             */
            tabClick(value) {
                this.$emit('input', value)
                this.changeTab(value)
            }
        },
        mounted() {
            if (this.tabItems.length) {
                this.tabItems[this.activeTab].isActive = true
            }
        },
        template: `
    <div class="b-tabs" :class="{ 'is-fullwidth': expanded }">
        <nav class="tabs" :class="navClasses">
            <ul>
                <li
                    v-for="(tabItem, index) in tabItems"
                    :key="index"
                    v-show="tabItem.visible"
                    :class="{ 'is-active': activeTab === index, 'is-disabled': tabItem.disabled }">
                    <a @click="tabClick(index)">
                        <span>[[ tabItem.label ]]</span>
                    </a>
                </li>
            </ul>
        </nav>
        <section class="tab-content">
            <slot/>
        </section>
    </div>`
    });

    Vue.component('tab-item', {
        delimiters:['[[', ']]'],
        props: {
            label: String,
            //icon: String,
            //iconPack: String,
            disabled: Boolean,
            visible: {
                type: Boolean,
                default: true
            }
        },
        data() {
            return {
                isActive: false,
                transitionName: null
            }
        },
        methods: {
            /**
             * Activate tab, alter animation name based on the index.
             */
            activate(oldIndex, index) {
                if (!this.$parent.animated) {
                    this.transitionName = null
                } else {
                    this.transitionName = index < oldIndex
                        ? 'slide-next'
                        : 'slide-prev'
                }
                this.isActive = true
            },
            /**
             * Deactivate tab, alter animation name based on the index.
             */
            deactivate(oldIndex, index) {
                if (!this.$parent.animated) {
                    this.transitionName = null
                } else {
                    this.transitionName = index < oldIndex
                        ? 'slide-next'
                        : 'slide-prev'
                }
                this.isActive = false
            }
        },
        created() {
            if (!this.$parent.$data._isTabs) {
                this.$destroy()
                throw new Error('You should wrap bTabItem on a bTabs')
            }
            this.$parent.tabItems.push(this)
        },
        beforeDestroy() {
            const index = this.$parent.tabItems.indexOf(this)
            if (index >= 0) {
                this.$parent.tabItems.splice(index, 1)
            }
        },
        template: `
<div>
    <transition :name="transitionName">
        <div v-show="isActive && visible" class="tab-item">
            <slot/>
        </div>
    </transition>
</div>`
    })
</script>

templates/footer.html
<footer class="footer" style="background-color: rgb(66,66,66); padding-top: 0.7rem; padding-bottom: 2rem">
    <div id="newBottomHtml" class="container only-desktop">
        <div class="level" style="padding-top: 0px; margin-bottom: 0px">
            <div class="level-item"><div class="hyky item">
                <p class="ftit">华亚快印</p>
                <p style="color: #b3b3b3">网络商务快印供应商</p>
            </div></div>
            <div class="level-item"><div class="zlbz item">
                <p class="ftit">华亚品质保证</p>
                <p style="color: #b3b3b3">华亚快印向广大客户承诺，产品保质、保量</p>
            </div></div>
            <div class="level-item"><div class="txfw item">
                <p class="ftit">贴心服务</p>
                <p style="color: #b3b3b3">一对一客户服务，让您下单无忧</p>
            </div></div>
        </div>

        <div class="footer-border"></div>

        <div class="footer-help columns" style="padding-left: 0;">
            <dl class="column" style="padding-left: 70px;">
                <dt><a>新手指南</a></dt>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=4" target="_blank">新手登录注册</a></dd>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=4" target="_blank">常见问题</a></dd>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=5" target="_blank">发票须知</a></dd>
                <!--  <dd><a href="/default/news/show?id=1" target="_blank">标准文档格式下载</a></dd>-->
            </dl>
            <dl class="column">
                <dt><a>订购流程</a></dt>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=6" target="_blank">下单流程</a></dd>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=7" target="_blank">退换货条款</a></dd>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=8" target="_blank">常见问题</a></dd>
                <!--<dd><a href="/default/news/show?id=1" target="_blank">标准文档格式下载</a></dd>-->
            </dl>
            <dl class="column">
                <dt><a>物流配送</a></dt>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=9" target="_blank">上门自取</a></dd>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=10" target="_blank">送货网点</a></dd>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=1" target="_blank">配送车队</a></dd>
                <dd><a href="javascript:void(0);" onclick="alert('请登录后，在会员中心订单管理中查看！');">货品查询</a></dd>
            </dl>
            <dl class="column">
                <dt><a>售后服务</a></dt>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=7" target="_blank">重印保证</a></dd>
                <dd><a href="http://www.gdhuaya.com/default/jianyi" target="_blank">投诉建议</a></dd>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=11" target="_blank">法律申明</a></dd>
                <dd><a href="http://www.gdhuaya.com/member/index/findpwd" target="_blank">忘记密码</a></dd>
            </dl>
            <dl class="column">
                <dt><a>帮助中心</a></dt>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=12" target="_blank">更多帮助信息</a></dd>
                <dd><a href="http://www.gdhuaya.com/default/news/show?id=13" target="_blank">常见问题</a></dd>
            </dl>
            <dl class="column last">
                <dt><a>客服服务</a></dt>
                <!-- <dd class=""><a href="/default/news/show?id=1" target="_blank">帮助中心</a></dd>-->
                <dd class=""><a href="tencent://message/?uin=800005246&amp;Site=www.gdhuaya.com&amp;Menu=yes"><img
                        src="/static/img/icon003.png" alt="" width="90px;" height="32px;"></a></dd>
            </dl>
        </div>
        <div style="width: 100%;text-align: center;margin-top: 30px;font-size: 50px;display: none;" id="pcserver">
            <a href="http://m.gdhuaya.com/" style="color: #fff;">手机端</a>
        </div>

        <div class="has-text-centered is-size-7">
            <p>
                <a href="http://www.gdhuaya.com/default/news/show?id=1">关于华亚</a>
                <span>|</span>
                <a href="http://www.gdhuaya.com/default/news/show?id=101">联系我们</a>
                <span>|</span>
                <a href="http://www.gdhuaya.com/default/news/show?id=11">服务条款</a>
                <span>|</span>
                <a href="http://www.gdhuaya.com/default/news/show?id=8">常见问题</a>
                <span>|</span>
                <a href="http://www.gdhuaya.com/default/jianyi">投诉建议</a>
                <!--  <span>|</span>
                  <a href="">客服中心</a>-->
                <!--     <span>|</span>
                     <a href="#">网站导航</a>-->
            </p>
        </div>
        <div class="has-text-centered is-size-7">
            <p>广东华亚印刷有限公司 <a href="http://www.miitbeian.gov.cn/" target="_blank">粤ICP备14051425号-1</a></p>
        </div>
    </div>

    <style>
        .item {
            padding: 10px 0px 10px 65px;
            display: inline;
            {#float: left;#}
            font-size: 13px;
        }
        .ftit {
            line-height: 36px;
            font-size: 18px;
            font-weight: bold;
            color: #b3b3b3;
        }
        .hyky {
            background: url("/static/img/index1.png") no-repeat -222px -3px;
            /*margin: 0px 70px 0px 70px;*/
        }
        .zlbz {
            background: url("/static/img/index1.png") no-repeat -225px -82px;
            /*margin: 0px 80px 0px 100px;*/
        }
        .txfw {
            background: url("/static/img/index1.png") no-repeat -219px -233px;
            /*margin: 0px 10px 0px 40px;*/
        }
        .footer-border {
            margin: 10px auto;
            border-top: 2px solid #b3b3b3;
        }
        footer *{
            color: #b3b3b3;
        }
        footer a {
            color: #b3b3b3;
            line-height: 24px;
        }
        footer a:hover {
            color: #ffffff;
        }.footer .footer-help dl dd a {
            line-height: 24px;
            color: #b3b3b3;
            font-size: 13px;
        }.footer .footer-help dl dt a {
            line-height: 24px;
            color: #b3b3b3;
            font-size: 15px;
            font-weight: bold;
        }.footer .footer-help dl a:hover {
            text-decoration: blink;
            color: #fff;
        }
    </style>
</footer>

templates/header.html
<!-- 公告 -->
<div class="container only-desktop" id="gonggao">
    {% if notifications %}
    <notification><h2>测试公告vue</h2></notification>
    {% endif %}
</div>
<!-- 顶层小菜单导航 -->
<div class="has-background-light">
    <nav class="container only-desktop level is-size-7">
        <div class="level-left">
            <div class="level-item">
                欢迎来到<a class="button is-light is-small" href="/">中山快印网</a>！
            </div>
        </div>
        <div class="level-right">
            {% if user.is_authenticated %}
            <a class="is-small" href="/userinfo/">{{ user.username }}</a>
            <a class="button is-light is-small" href="/logout/">退出</a>
            {% else %}
            <a class="button is-light is-small" href="/login/">登录</a>
            <span>|</span>
            <a class="button is-light is-small" href="/login/">注册</a>
            {% endif %}
            <span>|</span>
            <a class="button is-light is-small" href="/">网站首页</a>
            <span>|</span>
            <a class="button is-light is-small" href="#/orders/?starttime=2018-10-01&amp;endtime=2018-10-08">我的订单</a>
            <span>|</span>
            <a class="button is-light is-small" href="#" style="color: red">投诉建议</a>
            <span>|</span>
            <a class="button is-light is-small" href="/about/">关于华亚</a>
            <span>|</span>
            <a class="button is-light is-small" href="/about/">企业介绍</a>
            <span>|</span>
            <a class="button is-light is-small" href="#">帮助中心</a>
        </div>
    </nav>
</div>

<!-- logo 导航 -->
<div class="container only-desktop level" style="padding-top: 1.5rem;">
        <div class="level-left">
            <div>
                <img alt="华亚快印--商务印刷网" src="/static/img/logo.png">
            </div>
{#            <div style="width:240px;height:62px;position:absolute;top:20px;left:291px;">#}
{#                <img src="statics/20180412164313_61226.png">#}
{#            </div>#}
        </div>
{#        <div class="city_pg fl">#}
{#            <span class="ct s_none">广东站</span>#}
{##}
{#            <div id="btn_qhzd" class="qhzd s_none h20">切换城市#}
{#                <div class="yc_div" style="display: none"></div>#}
{#                <div id="qhzd_list" style="display: none" class="qhzdlist">#}
{#                    <div class="rm s_none">热门城市</div>#}
{#                    <ul id="city_name" class="mb28">#}
{#                        <li><a title="广东站" href="http://www.gdhuaya.com/">广东站</a></li>#}
{#                        <li><a title="成都站" href="http://www.huaya028.com/">成都站</a></li>#}
{#                        <li><a title="昆明站" href="http://www.huaya0871.com/">昆明站</a></li>#}
{#                        <li><a title="贵阳站" href="http://www.huaya0851.com/">贵阳站</a></li>#}
{#                        <li><a title="海南站" href="http://www.huaya0898.com/">海南站</a></li>#}
{#                    </ul>#}
{#                </div>#}
{#            </div>#}
{##}
{#        </div>#}

        <div class="level-right">
            <div class="phone">
                <img title="这个是华亚企业QQ,欢迎加我!" alt="" src="/static/img/contact.png" width="546"
                     height="46" align="">
            </div>
        </div>

</div>


<div class="nav-box">
    <nav class="navbar only-desktop nav-main" role="navigation" aria-label="main navigation">
        <div class="navbar-menu">
            <div class="navbar-start">
                {% url 'home:index' as home_index %}
                {% url 'home:quote' as home_quote %}
                {% url 'home:download' as home_download %}
                {% url 'home:about' as home_about %}
                <nav-main :isactive="{% if request.path == home_index %}true{% else %}false{% endif %}"></nav-main>
                <a class="navbar-item nav-btn {% if request.path == home_index %}selected{% endif %}" href="{{ home_index }}">首页</a>
                <a class="navbar-item nav-btn {% if request.path == home_quote %}selected{% endif %}" href="{{ home_quote }}">在线报价</a>
                <a class="navbar-item nav-btn {% if request.path == home_download %}selected{% endif %}" href="{{ home_download }}">下载专区</a>
                <a class="navbar-item nav-btn {% if request.path == home_about %}selected{% endif %}" href="{{ home_about }}">关于</a>
            </div>
            <div class="navbar-end">
                <a class="navbar-item nav-btn nav-cart">购物车</a>
            </div>
        </div>
    </nav>
</div>

templates/home/download.html
{% extends 'base.html' %}

{% block styles %}
    <style type="text/css">
        .std-btn {
            width: 200px;
            height: 35px;
            line-height: 35px;
            border-radius: 5px;
        }
        .browser-btn {
            border: 1px solid #e6e6e6;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="only-desktop" style="padding: 10px 0 30px 0;">
        <div class="columns"><div class="column is-offset-one-third is-one-third">
            <p class="has-text-centered title is-6" style="margin-top: 30px;">华亚推荐浏览器下载</p>
        </div></div>
        <div class="columns is-multiline">
            <div class="column is-one-third has-text-centered">
                <a target="_blank" href="http://se.360.cn/">
                    <img class="browser-btn" src="/static/img/20180509100828_42099.jpg" alt="360浏览器"></a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a target="_blank" href="http://browser.qq.com/">
                    <img class="browser-btn" src="/static/img/20180509100809_93248.jpg" alt="QQ浏览器"></a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a target="_blank" href="http://ie.sogou.com/">
                    <img class="browser-btn" src="/static/img/20180509100849_11636.jpg" alt="搜狗浏览器"></a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a target="_blank" href="http://google.luozhongxu.com/">
                    <img class="browser-btn" src="/static/img/20180509100903_59210.png" alt="谷歌浏览器"></a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a target="_blank" href="http://www.firefox.com.cn/">
                    <img class="browser-btn" src="/static/img/20180509100930_23320.jpg" alt="火狐浏览器"></a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a target="_blank" href="http://www.ucliulanqi.org/">
                    <img class="browser-btn" src="/static/img/20180509101000_88574.jpg" alt="UC浏览器"></a>
            </div>
        </div>
        <p class="has-text-centered title is-6" style="margin-top: 30px;">华亚标准格式下载</p>
        <div class="columns is-multiline">
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/882817972ad041a47a270bb2134ac693.cdr" target="_blank">名片制作标准</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/9c782b9cc2a59764b06a542a67e4ca7c.cdr" target="_blank">标准A型折卡制作标准</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/d9c02daa0aa79fe73a836e46da514130.cdr" target="_blank">标准B型折卡制作标准</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/0f116fd845d0e64be0837cabd3c7a806.cdr" target="_blank">标准折页制作标准</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/60d6fee4a9dfd0eff421c09de5b99a8e.cdr" target="_blank">标准西式信封</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/e19edd537304660f3cd63341d93a779e.cdr" target="_blank">标准中式信封</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/8c17e147b714c643cb86f5cccd6ca139.cdr" target="_blank">画册摆放标准</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/592915463704df46f8e400032f595ff0.cdr" target="_blank">封套（文件夹）制作标准</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/7062398aac3979b93a025ffd57a5f60b.cdr" target="_blank">利是封制作标准</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/53f0ae16b575384d4c7e4e373a1908df.cdr" target="_blank">手提袋制作标准</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/c870cf3218d56dcb187df4df104ac4f7.cdr" target="_blank">纸杯空白模板</a>
            </div>
            <div class="column is-one-third has-text-centered">
                <a class="button is-danger std-btn" href="http://www.gdhuaya.com/upload/40251a36f1a08be0293a00b849280909.cdr" target="_blank">档案袋模版</a>
            </div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    {% include "components/tab.html" %}
{% endblock %}